name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.402

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="EdgeFavoritesToShortcuts-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish EdgeFavoritesToShortcuts/EdgeFavoritesToShortcuts.csproj --framework net6.0-windows --runtime "${{ matrix.target }}" --no-self-contained -p:PublishSingleFile=true -c Release -o "$release_name"

          # Pack files
          #if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            #7z a -tzip "${release_name}.zip" "./${release_name}/*"
          #else
          #tar czvf "${release_name}.tar.gz" "$release_name"
          #fi

          mv ./${release_name}/EdgeFavoritesToShortcuts.exe ./EdgeFavoritesToShortcuts.exe

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "EdgeFavoritesToShortcuts.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
